name: release

on:
  push:
    tags:
      - "*"

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm libarchive-tools
      - name: Build app and create artifacts
        run: |
          npm install
          npm run build:linux
          cp dist/*.AppImage "dist/pulse-remote-desktop.AppImage"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./dist/pulse-remote-desktop.AppImage
            ./dist/*.deb
            ./dist/*.rpm
            ./dist/*.pacman
